/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiAssistant: typeof import('./src/components/editor/AiAssistant.vue')['default']
    CreateWorkspaceDialog: typeof import('./src/components/workspace/CreateWorkspaceDialog.vue')['default']
    DocumentBreadcrumb: typeof import('./src/components/document/DocumentBreadcrumb.vue')['default']
    DocumentSidebar: typeof import('./src/components/document/DocumentSidebar.vue')['default']
    DocumentTreeItem: typeof import('./src/components/document/DocumentTreeItem.vue')['default']
    EditorTitleInput: typeof import('./src/components/document/EditorTitleInput.vue')['default']
    EditorToolbar: typeof import('./src/components/editor/EditorToolbar.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    ImageUploadDialog: typeof import('./src/components/editor/ImageUploadDialog.vue')['default']
    InviteMemberDialog: typeof import('./src/components/workspace/InviteMemberDialog.vue')['default']
    LoginForm: typeof import('./src/components/auth/LoginForm.vue')['default']
    RegisterForm: typeof import('./src/components/auth/RegisterForm.vue')['default']
    RemoteCursors: typeof import('./src/components/editor/RemoteCursors.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchPanel: typeof import('./src/components/editor/SearchPanel.vue')['default']
    SlashMenu: typeof import('./src/components/editor/SlashMenu.vue')['default']
    TiptapEditor: typeof import('./src/components/editor/TiptapEditor.vue')['default']
    TopBar: typeof import('./src/components/layout/TopBar.vue')['default']
    VersionHistory: typeof import('./src/components/editor/VersionHistory.vue')['default']
    WorkspaceCard: typeof import('./src/components/workspace/WorkspaceCard.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
